spring:
  mail:
    host: thecatmaincave.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  profiles:
    active: @spring-profile@
server:
  port: 8085