spring:
  mail:
    username: yourmail@gmail.com
    password: aSimplePAssword

app-mail:
  to: test-to@mail.com
  from: mail-from@mail.com

server:
  ssl:
    key-store: "tls/localhost.jks"
    key-store-password: changeit
