spring:
  mail:
    password: aSimplePAssword
    username: yourmail@gmail.com
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
